{
 "title": "OVH",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "account",
    "label": "account",
    "query": {
     "query": "label_values(ovh_instance_Status, account)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Spam Blocked IPs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "ovh_spam_blocked_ip", "legendFormat": "{{account}}" }
   ]
  },
  {
   "title": "Forecast cost",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(ovh_forecast_cost{project='total'}) by (account)",
     "legendFormat": "{{account}}"
    }
   ]
  },
  { "title": "$account", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "account" },
  {
   "title": "Active Instances",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (project) (ovh_instance_Status{project!='total', status='ACTIVE', account=~\"$account\"})",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "Forecast Instances cost",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (project) (ovh_forecast_cost{project!='total', ressource='instances', account=~\"$account\"})",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "Forecast Volumes cost",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (project) (ovh_forecast_cost{project!='total', ressource='volumes', account=~\"$account\"})",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "Not Active Instances",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (project) (ovh_instance_Status{project!='total', status!='ACTIVE', account=~\"$account\"})",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "Hourly Billing Instances",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (project) (ovh_instance_hourly_billing{project!='total', account=~\"$account\"})",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "Not attached Volumes",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (project) (ovh_volume_not_attached{project!='total', account=~\"$account\"})",
     "legendFormat": "{{project}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Live logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "{container_name=~\"^ovh_exporter.*\" }"
    }
   ]
  }
 ]
}