{
 "title": "OVH IPs mitigation",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "IP count on mitigation",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ovh_ipcount_onmitigation)" }
   ]
  },
  {
   "title": "IP on Mitigation",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "targets": [
    { "expr": "ovh_ip_onmitigation{} > 0", "legendFormat": "{{ip}}" }
   ]
  },
  {
   "title": "mitigation Pps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "max_over_time(ovh_ip_onmitigation_max_in_pps{}[2m])",
     "legendFormat": "IN [{{ip}}]"
    },
    {
     "expr": "max_over_time(ovh_ip_onmitigation_max_out_pps{}[2m])",
     "legendFormat": "Out [{{ip}}]"
    }
   ]
  },
  {
   "title": "mitigation Bps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "max_over_time(ovh_ip_onmitigation_max_in_bps{}[2m])",
     "legendFormat": "IN [{{ip}}]"
    },
    {
     "expr": "max_over_time(ovh_ip_onmitigation_max_out_bps{}[2m])",
     "legendFormat": "Out [{{ip}}]"
    }
   ]
  }
 ]
}